services:
  proxy:
    container_name: proxy
    init: true
    build:
      context: back/proxy
    networks:
      - one
    ports:
      - 3000:80
    environment:
      - FRONTEND_URL=http://frontend:5173
    restart: always
    env_file:
      - .env
    depends_on:
      - frontend

  frontend:
    container_name: frontend
    init: true
    build:
      context: front
    networks:
      - one
    expose:
      - 5173
    volumes:
      - ./front:/app
      - /app/node_modules
    restart: always
    env_file:
      - .env

networks:
  one:
    driver: bridge
